# Generated by Django 6.0.4 on 2026-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
