# Generated by Django 6.0.4 on 2026-06-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_patient_account_and_more'),
        ('appointment', '0002_timeslot_booked'),
    ]

    operations = [
    ]
